### ISSUE TITLE
Word and Synonym should not be same

### ISSUE THREAD

**Issue by maheshmnj** [maheshmnj/vocabhub#11]
Users can add the same word as synonym

**To Reproduce**
1. Add / Edit a word/
2. Add the same synonym as word
3. save/update

**Expected behavior**
Word and synonym should not be the same

**Comment by daumienebi** [comment]
Hey there!, are these issues still really open to be fixed?

**Comment by maheshmnj** [comment]
Hey @daumienebi, Yes, I intend to fix them, But unfortunately I cannot commit an eta. The latest updates to the app are here https://github.com/maheshmnj/vocabhub/tree/redesign.
I am open to contributions though.

**Comment by daumienebi** [comment]
Alright, i am trying to improve my flutter skills and i'm about to complete my first app to be published to the Play Store and i found your StackOverFlow profile where you answered a question that helped me so thanks!. I am open to contributing to your app in any possible way. I understand that newer commits are no longer pushed to the master branch right?

**Comment by maheshmnj** [comment]
Nice to hear that!

> I understand that newer commits are no longer pushed to the master branch right?

Actually, on master, I have a multiplatform app (android/web app) and on the redesig branch, it only is supported for mobile so I won't be merging the code to master unless the redesign branch supports web. If you ever make a PR please make it to the redesign branch.  I will update the contributing guidelines soon

**Comment by daumienebi** [comment]
Alright :)

**Comment by daumienebi** [comment]
Hey there, i wanted to ask a question about the usage of Supabase in this project. Are you personally hosting the database?

**Comment by maheshmnj** [comment]
@daumienebi No the hosting is taken care of by Supabase itself, I am just using the supabase client to interact with the database.

**Comment by daumienebi** [comment]
@maheshmnj Ok,thanks for the information.

**Comment by maheshmnj** [comment]
This has been fixed in the linked commit and will be released in the upcoming version

**Comment by daumienebi** [comment]
@maheshmnj Alright, nice to hear that :)

**Comment by maheshmnj** [comment]
@daumienebi that is strange! I just verified with two different accounts and it seems to work for me. Is the issue with any specific Google account on your end?

**Comment by daumienebi** [comment]
@maheshmnj Hey there, sorry for not responding all this while, i remembered this stuff once again and i tried with two different google accounts but it's not signing in. I dont know if any of those accounts were mistakenly blocked or something but i get the 'Failed to register new user' error. Here's a screenshot :

![Screenshot_2023-05-17-01-15-01-131_com vocabhub app](https://github.com/maheshmnj/vocabhub/assets/90214727/9f74fb0f-c6e1-4d01-ad3a-5290ea9967ea)

**Comment by daumienebi** [comment]
@maheshmnj Alright, i have created the issue here : #23
