### ISSUE TITLE
Error when trying to sign in

### ISSUE THREAD

**Issue by daumienebi** [maheshmnj/vocabhub#23]
**Describe the bug**
The "Failed to sign in user" error is thrown when i try to sign in with my Google account. I tried with 2 different accounts but the error still persists.

**To Reproduce**
1. Open the app
2. Click on 'Sign in with Google'

**Expected behavior**
I expected my account to be signed in.

**Screenshots**

![cap](https://github.com/maheshmnj/vocabhub/assets/90214727/9164004d-f9b0-4864-9204-cbf845bdb83a)

**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi Note 9 Pro]
 - OS: [e.g. Android 11 RKQ1.200826.002]

**Comment by maheshmnj** [comment]
Thanks for the report @daumienebi I will investigate this issue soon.

**Comment by maheshmnj** [comment]
@daumienebi I have submitted the fix and it should be available in the store shortly.

**Comment by maheshmnj** [comment]
The new release is now available in store, Closing as fixed. Feel free to write back in case you still encounter the issue.
cc: @daumienebi

**Comment by daumienebi** [comment]
Hello  @maheshmnj , i updated the app but i'm still getting the same log in error and can't access the words because the app gets stuck on the app screens with the Loading Indicator. I will attack a video so that you can have a look.

You can spot the "Failed to sign in new user" error at the beginning of the video.

https://github.com/maheshmnj/vocabhub/assets/90214727/f11afd6d-43ae-455c-9db3-cb61d8f18403

**Comment by maheshmnj** [comment]
Thanks for the quick feedback @daumienebi, I have submitted the new release I forgot to add the API keys in th arguments. so the app did not work in release but only in debug.

**Comment by maheshmnj** [comment]
I am seeking some ideas on this page, Once you are able to install the app. Please feel free to give your input on this issue https://github.com/maheshmnj/vocabhub/issues/24

**Comment by daumienebi** [comment]
I can now sign in correctly @maheshmnj . The app seems more complete now. Regarding the search page ideas, i might be able to look into it when i'm done with some exams i have soon.

**Comment by maheshmnj** [comment]
Glad you are able to signIn. 
> Regarding the search page ideas, i might be able to look into it when i'm done with some exams i have soon.

Sure no problem, Good luck with your exams I am sure you will do great. 
Hope to see you soon!
